from backend import db
from datetime import datetime
# player table and details
class Player(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date_updated = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    tag = db.Column(db.String(20), nullable=False)
    name = db.Column(db.String(50), nullable=False)
    town_hall_level = db.Column(db.Integer, nullable=False)
    town_hall_weapon_level = db.Column(db.Integer, nullable=False)
    exp_level = db.Column(db.Integer, nullable=False)
    trophies = db.Column(db.Integer, nullable=False)
    best_trophies = db.Column(db.Integer, nullable=False)
    war_stars = db.Column(db.Integer, nullable=False)
    attack_wins = db.Column(db.Integer, nullable=False)
    defence_wins= db.Column(db.Integer, nullable=False)
    builder_hall_level = db.Column(db.Integer, nullable=False)
    versus_trophies = db.Column(db.Integer, nullable=False)
    best_versus_trophies = db.Column(db.Integer, nullable=False)
    versus_battle_wins = db.Column(db.Integer, nullable=False)
    role = db.Column(db.String(50), nullable=False)
    donations = db.Column(db.Integer, nullable=False)
    donations_received = db.Column(db.Integer, nullable=False)
    clan_name = db.Column(db.String(50), nullable=False)
    clan_tag = db.Column(db.String(50), nullable=False)
    league = db.Column(db.JSON,nullable=False)
    legend_statistics = db.Column(db.JSON, nullable=False)
    achievements = db.Column(db.JSON, nullable=False)
    labels = db.Column(db.JSON, nullable=False)
    troops = db.Column(db.JSON, nullable=False)
    heroes = db.Column(db.JSON, nullable=False)
    spells = db.Column(db.JSON, nullable=False)
